// Code generated by protoc-gen-go.
// source: msg.proto
// DO NOT EDIT!

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	C2S_AddUser
	C2S_Message
	C2S_Action
	S2C_Login
	S2C_Joined
	S2C_Left
	S2C_Typing
	S2C_StopTyping
	S2C_Message
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type C2S_AddUser struct {
	UserName string `protobuf:"bytes,1,opt,name=UserName,json=userName" json:"UserName,omitempty"`
}

func (m *C2S_AddUser) Reset()                    { *m = C2S_AddUser{} }
func (m *C2S_AddUser) String() string            { return proto.CompactTextString(m) }
func (*C2S_AddUser) ProtoMessage()               {}
func (*C2S_AddUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type C2S_Message struct {
	Message string `protobuf:"bytes,1,opt,name=Message,json=message" json:"Message,omitempty"`
}

func (m *C2S_Message) Reset()                    { *m = C2S_Message{} }
func (m *C2S_Message) String() string            { return proto.CompactTextString(m) }
func (*C2S_Message) ProtoMessage()               {}
func (*C2S_Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type C2S_Action struct {
	// typing
	// stop typing
	Op string `protobuf:"bytes,1,opt,name=Op,json=op" json:"Op,omitempty"`
}

func (m *C2S_Action) Reset()                    { *m = C2S_Action{} }
func (m *C2S_Action) String() string            { return proto.CompactTextString(m) }
func (*C2S_Action) ProtoMessage()               {}
func (*C2S_Action) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type S2C_Login struct {
	NumUsers int32 `protobuf:"varint,1,opt,name=NumUsers,json=numUsers" json:"NumUsers,omitempty"`
}

func (m *S2C_Login) Reset()                    { *m = S2C_Login{} }
func (m *S2C_Login) String() string            { return proto.CompactTextString(m) }
func (*S2C_Login) ProtoMessage()               {}
func (*S2C_Login) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type S2C_Joined struct {
	NumUsers int32  `protobuf:"varint,1,opt,name=NumUsers,json=numUsers" json:"NumUsers,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=UserName,json=userName" json:"UserName,omitempty"`
}

func (m *S2C_Joined) Reset()                    { *m = S2C_Joined{} }
func (m *S2C_Joined) String() string            { return proto.CompactTextString(m) }
func (*S2C_Joined) ProtoMessage()               {}
func (*S2C_Joined) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type S2C_Left struct {
	NumUsers int32  `protobuf:"varint,1,opt,name=NumUsers,json=numUsers" json:"NumUsers,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=UserName,json=userName" json:"UserName,omitempty"`
}

func (m *S2C_Left) Reset()                    { *m = S2C_Left{} }
func (m *S2C_Left) String() string            { return proto.CompactTextString(m) }
func (*S2C_Left) ProtoMessage()               {}
func (*S2C_Left) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type S2C_Typing struct {
	UserName string `protobuf:"bytes,1,opt,name=UserName,json=userName" json:"UserName,omitempty"`
}

func (m *S2C_Typing) Reset()                    { *m = S2C_Typing{} }
func (m *S2C_Typing) String() string            { return proto.CompactTextString(m) }
func (*S2C_Typing) ProtoMessage()               {}
func (*S2C_Typing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type S2C_StopTyping struct {
	UserName string `protobuf:"bytes,1,opt,name=UserName,json=userName" json:"UserName,omitempty"`
}

func (m *S2C_StopTyping) Reset()                    { *m = S2C_StopTyping{} }
func (m *S2C_StopTyping) String() string            { return proto.CompactTextString(m) }
func (*S2C_StopTyping) ProtoMessage()               {}
func (*S2C_StopTyping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type S2C_Message struct {
	UserName string `protobuf:"bytes,1,opt,name=UserName,json=userName" json:"UserName,omitempty"`
	Message  string `protobuf:"bytes,2,opt,name=Message,json=message" json:"Message,omitempty"`
}

func (m *S2C_Message) Reset()                    { *m = S2C_Message{} }
func (m *S2C_Message) String() string            { return proto.CompactTextString(m) }
func (*S2C_Message) ProtoMessage()               {}
func (*S2C_Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto.RegisterType((*C2S_AddUser)(nil), "msg.C2S_AddUser")
	proto.RegisterType((*C2S_Message)(nil), "msg.C2S_Message")
	proto.RegisterType((*C2S_Action)(nil), "msg.C2S_Action")
	proto.RegisterType((*S2C_Login)(nil), "msg.S2C_Login")
	proto.RegisterType((*S2C_Joined)(nil), "msg.S2C_Joined")
	proto.RegisterType((*S2C_Left)(nil), "msg.S2C_Left")
	proto.RegisterType((*S2C_Typing)(nil), "msg.S2C_Typing")
	proto.RegisterType((*S2C_StopTyping)(nil), "msg.S2C_StopTyping")
	proto.RegisterType((*S2C_Message)(nil), "msg.S2C_Message")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2d, 0x4e, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x06, 0x32, 0x95, 0x34, 0xb9, 0xb8, 0x9d, 0x8d, 0x82,
	0xe3, 0x1d, 0x53, 0x52, 0x42, 0x8b, 0x53, 0x8b, 0x84, 0xa4, 0xb8, 0x38, 0x40, 0xb4, 0x5f, 0x62,
	0x6e, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x47, 0x29, 0x94, 0xaf, 0xa4, 0x0e, 0x51,
	0xea, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x9e, 0x2a, 0x24, 0xc1, 0xc5, 0x0e, 0x65, 0x42, 0x55, 0xb2,
	0xe7, 0x42, 0xb8, 0x4a, 0x32, 0x5c, 0x5c, 0x60, 0x33, 0x93, 0x4b, 0x32, 0xf3, 0xf3, 0x84, 0xf8,
	0xb8, 0x98, 0xfc, 0x0b, 0xa0, 0x4a, 0x98, 0xf2, 0x0b, 0x80, 0xc6, 0x70, 0x06, 0x1b, 0x39, 0xc7,
	0xfb, 0xe4, 0xa7, 0x67, 0xe6, 0x81, 0xec, 0xf3, 0x2b, 0xcd, 0x05, 0x59, 0x59, 0x0c, 0x56, 0xc2,
	0x1a, 0xc4, 0x91, 0x07, 0xe5, 0x2b, 0xb9, 0x70, 0x71, 0x81, 0x14, 0x7a, 0xe5, 0x67, 0xe6, 0xa5,
	0xa6, 0xe0, 0x53, 0x89, 0xe2, 0x6a, 0x26, 0x34, 0x57, 0x3b, 0x71, 0x71, 0x80, 0xad, 0x4b, 0x4d,
	0x2b, 0x21, 0xdb, 0x0c, 0x0d, 0x88, 0x4b, 0x42, 0x2a, 0x0b, 0x32, 0xf3, 0xd2, 0xf1, 0x86, 0x91,
	0x0e, 0x17, 0x1f, 0x48, 0x65, 0x70, 0x49, 0x7e, 0x01, 0x11, 0xaa, 0x9d, 0xb9, 0xb8, 0x41, 0xaa,
	0x61, 0x21, 0x8a, 0x47, 0x29, 0x72, 0x68, 0x33, 0xa1, 0x84, 0x76, 0x12, 0x1b, 0x38, 0x36, 0x8d,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x1b, 0x21, 0x97, 0xda, 0x01, 0x00, 0x00,
}
